// AUTO-GENERATED by scripts/generateTypes.js — do not edit by hand.
// Concrete interfaces mirroring the program IDL (anchor camelCase fields).
/* eslint-disable @typescript-eslint/no-explicit-any */
import { BN } from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";

export interface AddCollateralErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface AddCollateralErParams {
  collateralDelta: BN;
}

export interface AddCollateralLog {
  owner: PublicKey;
  market: PublicKey;
  collateralAmount: BN;
  collateralPriceUsd: BN;
}

export interface AddCollateralLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface AddCollateralLogV2 {
  owner: PublicKey;
  market: PublicKey;
  collateralAmount: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
}

export interface AddCollateralLogV3 {
  owner: PublicKey;
  market: PublicKey;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  finalCollateralAmount: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface AddCollateralQuoteData {
  amountIn: BN;
  collateralDeltaUsd: BN;
  existingCollateralUsd: BN;
  existingLeverage: BN;
  existingLiquidationPrice: OraclePrice;
  newCollateralUsd: BN;
  newLeverage: BN;
  newLiquidationPrice: OraclePrice;
  maxAddableUsd: BN;
  swapRequired: boolean;
  swapPossible: boolean;
  passesMinCollateral: boolean;
  passesLeverageCheck: boolean;
}

export interface AddCompoundingLiquidityErLog {
  poolName: string;
  owner: PublicKey;
  inCustodyUid: BN;
  amountIn: BN;
  rewardAmount: BN;
  userLp: BN;
  rewardLp: BN;
  compoundingOut: BN;
  feeAmount: BN;
  compoundingPriceUsd: BN;
  tokenInPrice: BN;
  tokenInPriceExponent: number;
  slippageOk: boolean;
}

export interface AddCompoundingLiquidityLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  amountIn: BN;
  compoundingAmountOut: BN;
  feeAmount: BN;
  rewardPerLpStaked: BN;
  compoundingPriceUsd: BN;
  tokenInPrice: BN;
  tokenInPriceExponent: number;
}

export interface AddCompoundingLiquiditySettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  inCustodyId: number;
  userLp: BN;
  rewardLp: BN;
  compoundingOut: BN;
  amountReturned: BN;
}

export interface AddCompoundingLiquidityWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  inCustodyUid: BN;
  rewardCustodyUid: BN;
  amountIn: BN;
  minCompoundingAmountOut: BN;
}

export interface AddCompoundingLiquidityWithActionParams {
  amountIn: BN;
  minCompoundingAmountOut: BN;
  queueErAction: boolean;
}

export interface AddCustodyErLog {
  pool: PublicKey;
  custody: PublicKey;
  custodyUid: number;
  uniqueCustodyCount: number;
}

export interface AddCustodyErParams {
  ratios: TokenRatios[];
}

export interface AddCustodyParams {
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  token22: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  ratios: TokenRatios[];
  tokenAmountMultiplier: BN;
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
}

export interface AddCustodyToken22AccountParams {
  tokenAccountSpace: BN;
}

export interface AddInternalOracleParams {
  expo: number;
  lazerFeedId: number;
}

export interface AddLiquidityAndStakeErLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  amountIn: BN;
  lpAmountOut: BN;
  feeAmount: BN;
  lpPriceUsd: BN;
  tokenInPrice: BN;
  tokenInPriceExponent: number;
  slippageOk: boolean;
}

export interface AddLiquidityAndStakeLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  amountIn: BN;
  lpAmountOut: BN;
  feeAmount: BN;
  lpPriceUsd: BN;
  tokenInPrice: BN;
  tokenInPriceExponent: number;
}

export interface AddLiquidityAndStakeSettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  custodyId: number;
  lpAmount: BN;
  amountReturned: BN;
}

export interface AddLiquidityAndStakeWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  amountIn: BN;
  minLpAmountOut: BN;
}

export interface AddLiquidityAndStakeWithActionParams {
  amountIn: BN;
  minLpAmountOut: BN;
  queueErAction: boolean;
}

export interface AddLiquidityLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  amountIn: BN;
  lpAmountOut: BN;
  feeAmount: BN;
}

export interface AddLiquidityLogV2 {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  amountIn: BN;
  lpAmountOut: BN;
  feeAmount: BN;
  lpPriceUsd: BN;
  tokenInPrice: BN;
  tokenInPriceExponent: number;
}

export interface AddMarketErLog {
  pool: PublicKey;
  market: PublicKey;
  targetCustody: PublicKey;
  collateralCustody: PublicKey;
  side: number;
  targetCustodyUid: number;
  collateralCustodyUid: number;
}

export interface AddMarketErParams {
}

export interface AddMarketParams {
  side: Side;
  correlation: boolean;
  maxPayoffBps: BN;
  permissions: MarketPermissions;
}

export interface AddPoolParams {
  name: string;
  permissions: Permissions;
  maxAumUsd: BN;
  metadataTitle: string;
  metadataSymbol: string;
  metadataUri: string;
  stakingFeeShareBps: BN;
  vpVolumeFactor: number;
  stakingFeeBoostBps: BN[];
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  thresholdUsd: BN;
}

export interface AmountAndFee {
  amount: BN;
  fee: BN;
}

export interface Assets {
  collateral: BN;
  owned: BN;
  locked: BN;
}

export interface Basket {
  owner: PublicKey;
  delegate: PublicKey;
  basketBump: number;
  padding: number[];
  positionsActive: boolean;
  ordersActive: boolean;
  debits: Ledger[];
  pendingCredits: Ledger[];
  positions: PositionMeta[];
  orders: OrderMeta[];
}

export interface BasketLedgerErLog {
  owner: PublicKey;
  basket: PublicKey;
  tokenMint: PublicKey;
  debitAmount: BN;
  creditAmount: BN;
  opType: number;
}

export interface BasketOrder {
  limitOrders: LimitOrder[];
  takeProfitOrders: TriggerOrder[];
  stopLossOrders: TriggerOrder[];
  isInitialised: boolean;
  isActive: boolean;
  openSl: number;
  openTp: number;
  inactiveSl: number;
  inactiveTp: number;
  activeOrders: number;
  referenceTimestamp: BN;
  executionCount: BN;
  padding: BN[];
}

export interface BatchDelegateFlpStakeLog {
  processed: number;
  skipped: number;
}

export interface BatchDelegateFlpStakeParams {
}

export interface BatchDelegateFlpStakeUserLog {
  flpStake: PublicKey;
  owner: PublicKey;
  pool: PublicKey;
}

export interface BatchDelegateTokenStakeLog {
  processed: number;
  skipped: number;
}

export interface BatchDelegateTokenStakeParams {
}

export interface BatchDelegateTokenStakeUserLog {
  tokenStake: PublicKey;
  owner: PublicKey;
}

export interface BorrowRateParams {
  baseRate: BN;
  slope1: BN;
  slope2: BN;
  optimalUtilization: BN;
}

export interface BorrowRateState {
  currentRate: BN;
  cumulativeLockFee: BN;
  lastUpdate: BN;
}

export interface BurnAndClaimLog {
  owner: PublicKey;
  nftMint: PublicKey;
  claimAmount: BN;
  currentTimestamp: BN;
}

export interface BurnAndStakeLog {
  owner: PublicKey;
  nftMint: PublicKey;
  tokenStake: PublicKey;
  stakeAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
}

export interface CancelAllTriggerOrdersErParams {
  market: PublicKey;
}

export interface CancelLimitOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  reserveUsd: BN;
  stopLossPrice: BN;
  stopLossPriceExponent: number;
  takeProfitPrice: BN;
  takeProfitPriceExponent: number;
  receiveCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface CancelLimitOrderErParams {
  market: PublicKey;
  orderId: number;
}

export interface CancelLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  reserveUsd: BN;
  stopLossPrice: BN;
  stopLossPriceExponent: number;
  takeProfitPrice: BN;
  takeProfitPriceExponent: number;
  receiveCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface CancelTriggerOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  receiveCustodyUid: number;
  isStopLoss: boolean;
}

export interface CancelTriggerOrderErParams {
  market: PublicKey;
  orderId: number;
  isStopLoss: boolean;
}

export interface CancelTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  receiveCustodyUid: number;
  isStopLoss: boolean;
}

export interface CancelUnstakeTokenRequestErLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  amount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface CancelUnstakeTokenRequestErParams {
  withdrawRequestId: number;
}

export interface CancelUnstakeTokenRequestLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  amount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
}

export interface CancelUnstakeTokenRequestLogV2 {
  owner: PublicKey;
  tokenStake: PublicKey;
  amount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface CloseAndSwapLog {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  exitFeeAmount: BN;
  receiveCustodyUid: BN;
  receiveAmount: BN;
  swapFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface CloseAndSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  outputCustodyUid: number;
  outputAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  lockedAmount: BN;
  padding: BN[];
}

export interface CloseLegacyOrderAccountErLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  order: PublicKey;
  migrated: boolean;
  empty: boolean;
}

export interface CloseLegacyOrderAccountErParams {
}

export interface CloseLegacyPositionAccountErLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  position: PublicKey;
  migrated: boolean;
  empty: boolean;
}

export interface CloseLegacyPositionAccountErParams {
}

export interface ClosePositionErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  outputCustodyUid: number;
  outputAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  lockedAmount: BN;
  padding: BN[];
}

export interface ClosePositionErParams {
  priceWithSlippage: OraclePrice;
  privilege: Privilege;
}

export interface ClosePositionLog {
  owner: PublicKey;
  market: PublicKey;
  priceUsd: BN;
  sizeAmount: BN;
  sizeUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
}

export interface ClosePositionLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  lockedAmount: BN;
  padding: BN[];
}

export interface ClosePositionLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
}

export interface ClosePositionLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  exitFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface ClosePositionQuoteData {
  receiveTokenAmount: BN;
  receiveTokenAmountUsd: BN;
  markPrice: OraclePrice;
  entryPrice: OraclePrice;
  existingLiquidationPrice: OraclePrice;
  newLiquidationPrice: OraclePrice;
  existingSize: BN;
  newSize: BN;
  existingCollateralUsd: BN;
  newCollateralUsd: BN;
  existingLeverage: BN;
  newLeverage: BN;
  settledPnlUsd: BN;
  isProfitable: boolean;
  profitUsd: BN;
  lossUsd: BN;
  fees: BN;
  feesBeforeDiscount: BN;
  exitFeeUsd: BN;
  exitFeeBeforeDiscountUsd: BN;
  lockAndUnsettledFeeUsd: BN;
  priceImpactUsd: BN;
  isSolvent: boolean;
  swapRequired: boolean;
  swapPossible: boolean;
  isPartialClose: boolean;
}

export interface CollectRebateErLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  rebateAmount: BN;
  rebateUsd: BN;
}

export interface CollectRebateLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  rebateAmount: BN;
  rebateUsd: BN;
  padding: BN[];
}

export interface CollectRebateReceipt {
  owner: PublicKey;
  rebateVault: PublicKey;
  rebateMint: PublicKey;
  claimAmount: BN;
  claimUsd: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CollectRebateSettleBaseLog {
  owner: PublicKey;
  rebateAmount: BN;
  rebateUsd: BN;
}

export interface CollectRebateWithActionBaseLog {
  owner: PublicKey;
  rebateMint: PublicKey;
}

export interface CollectRebateWithActionParams {
}

export interface CollectRevenueErLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  revenueAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
  lastEpochCount: number;
}

export interface CollectRevenueLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  revenueAmount: BN;
  lastEpochCount: number;
  padding: BN[];
}

export interface CollectRevenueLogV2 {
  owner: PublicKey;
  tokenStake: PublicKey;
  revenueAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
  lastEpochCount: number;
}

export interface CollectRevenueReceipt {
  owner: PublicKey;
  tokenVault: PublicKey;
  revenueMint: PublicKey;
  claimAmount: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CollectRevenueSettleBaseLog {
  owner: PublicKey;
  revenueAmount: BN;
}

export interface CollectRevenueWithActionBaseLog {
  owner: PublicKey;
  revenueMint: PublicKey;
}

export interface CollectRevenueWithActionParams {
}

export interface CollectStakeRewardErLog {
  owner: PublicKey;
  poolName: string;
  rewardMint: PublicKey;
  inlineRefreshCredit: BN;
  claimAmount: BN;
}

export interface CollectStakeRewardLog {
  owner: PublicKey;
  poolName: string;
  rewardAmount: BN;
  rewardMint: PublicKey;
}

export interface CollectStakeRewardLogV2 {
  owner: PublicKey;
  poolName: string;
  rewardAmount: BN;
  rewardMint: PublicKey;
  rewardShare: BN;
}

export interface CollectStakeRewardReceipt {
  pool: PublicKey;
  owner: PublicKey;
  rewardMint: PublicKey;
  claimAmount: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CollectStakeRewardSettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  rewardMint: PublicKey;
  claimAmount: BN;
}

export interface CollectStakeRewardWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  rewardMint: PublicKey;
}

export interface CollectStakeRewardWithActionParams {
}

export interface CollectTokenRewardErLog {
  owner: PublicKey;
  amount: BN;
  allowed: boolean;
}

export interface CollectTokenRewardLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  amount: BN;
  lastEpochCount: number;
  padding: BN[];
}

export interface CollectTokenRewardReceipt {
  owner: PublicKey;
  tokenMint: PublicKey;
  amount: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CollectTokenRewardSettleBaseLog {
  owner: PublicKey;
  amount: BN;
}

export interface CollectTokenRewardWithActionBaseLog {
  owner: PublicKey;
}

export interface CollectTokenRewardWithActionParams {
}

export interface CompoundFeesErLog {
  poolName: string;
  keeper: PublicKey;
  rewardAmount: BN;
  rewardLpAmount: BN;
  rewardPerLpStaked: BN;
  lpPriceUsd: BN;
  compoundingPriceUsd: BN;
}

export interface CompoundFeesLog {
  poolName: string;
  rewardAmount: BN;
  rewardLpAmount: BN;
  rewardPerLpStaked: BN;
  lpPriceUsd: BN;
  compoundingPriceUsd: BN;
}

export interface CompoundFeesReceipt {
  pool: PublicKey;
  keeper: PublicKey;
  rewardAmount: BN;
  rewardLpToMint: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CompoundFeesSettleBaseLog {
  pool: PublicKey;
  keeper: PublicKey;
  rewardLpAmount: BN;
}

export interface CompoundFeesWithActionBaseLog {
  poolName: string;
  keeper: PublicKey;
}

export interface CompoundFeesWithActionParams {
  queueErAction: boolean;
}

export interface CompoundingDepositReceipt {
  pool: PublicKey;
  liquidityProvider: PublicKey;
  inTokenMint: PublicKey;
  amountIn: BN;
  minCompoundingAmountOut: BN;
  rewardAmount: BN;
  rewardLpToMint: BN;
  userLpToMint: BN;
  compoundingToMint: BN;
  feeAmount: BN;
  inCustodyId: number;
  rewardCustodyId: number;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CompoundingStats {
  activeAmount: BN;
  totalSupply: BN;
  rewardSnapshot: BN;
  feeShareBps: BN;
  lastCompoundTime: BN;
}

export interface CompoundingTokenData {
  lpPrice: BN;
  compoundingPrice: BN;
  ratios: BN[];
}

export interface CompoundingWithdrawReceipt {
  pool: PublicKey;
  liquidityProvider: PublicKey;
  outTokenMint: PublicKey;
  custodyTokenAccount: PublicKey;
  compoundingAmountIn: BN;
  minTokenAmountOut: BN;
  rewardAmount: BN;
  rewardLpMinted: BN;
  outLpToRedeem: BN;
  outTokenAmount: BN;
  feeAmount: BN;
  outCustodyId: number;
  rewardCustodyId: number;
  bump: number;
  processed: number;
  padding: number[];
}

export interface CreateReferralParams {
}

export interface CreateWhitelistParams {
  isSwapFeeExempt: boolean;
  isDepositFeeExempt: boolean;
  isWithdrawalFeeExempt: boolean;
  poolAddress: PublicKey;
}

export interface Custody {
  pool: PublicKey;
  mint: PublicKey;
  tokenAccount: PublicKey;
  decimals: number;
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  tokenAmountMultiplier: BN;
  assets: Assets;
  feesStats: FeesStats;
  borrowRateState: BorrowRateState;
  bump: number;
  tokenAccountBump: number;
  token22: boolean;
  uid: number;
  reservedAmount: BN;
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
  tradeReceivable: BN;
  tradePayable: BN;
  padding: number[];
}

export interface CustodySettlementErLog {
  pool: PublicKey;
  custody: PublicKey;
  tokenMint: PublicKey;
  netAmount: BN;
  custodyToVault: boolean;
}

export interface CustodySettlementReceipt {
  pool: PublicKey;
  custody: PublicKey;
  tokenMint: PublicKey;
  netAmount: BN;
  custodyToVault: boolean;
  processed: number;
  bump: number;
  padding: number[];
}

export interface CustodySettlementSettleBaseLog {
  pool: PublicKey;
  custody: PublicKey;
  tokenMint: PublicKey;
  netAmount: BN;
  custodyToVault: boolean;
}

export interface CustodySettlementWithActionBaseLog {
  pool: PublicKey;
  custody: PublicKey;
  tokenMint: PublicKey;
}

export interface CustodySettlementWithActionParams {
}

export interface CustomOracle {
  price: BN;
  expo: number;
  conf: BN;
  ema: BN;
  publishTime: BN;
  lazerFeedId: number;
  lazerPrice: BN;
  Reserved: number[];
}

export interface DecreasePositionSizeErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  deltaLockedAmount: BN;
  outputAmount: BN;
  outputCustodyUid: number;
  padding: BN[];
}

export interface DecreasePositionSizeErParams {
  priceWithSlippage: OraclePrice;
  sizeDelta: BN;
  privilege: Privilege;
}

export interface DecreaseSizeLog {
  owner: PublicKey;
  market: PublicKey;
  priceUsd: BN;
  sizeDelta: BN;
  sizeDeltaUsd: BN;
  settledReturns: BN;
  deltaProfitUsd: BN;
  deltaLossUsd: BN;
  feeAmount: BN;
}

export interface DecreaseSizeLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  deltaLockedAmount: BN;
  padding: BN[];
}

export interface DecreaseSizeLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeDelta: BN;
  sizeDeltaUsd: BN;
  settledReturns: BN;
  deltaProfitUsd: BN;
  deltaLossUsd: BN;
  feeAmount: BN;
}

export interface DecreaseSizeLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  exitFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface DelegateBasketLog {
  owner: PublicKey;
  basket: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegateBasketParams {
}

export interface DelegateCustodyLog {
  custody: PublicKey;
  pool: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegateCustodyParams {
}

export interface DelegateInternalOracleLog {
  oracleAccount: PublicKey;
  custodyTokenMint: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegateInternalOracleParams {
}

export interface DelegateMarketLog {
  market: PublicKey;
  targetCustody: PublicKey;
  collateralCustody: PublicKey;
  side: number;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegateMarketParams {
}

export interface DelegatePoolLog {
  pool: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegatePoolParams {
}

export interface DelegateReallocVaultLog {
  reallocVault: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
  fundingLamports: BN;
}

export interface DelegateReallocVaultParams {
  fundingLamports: BN;
}

export interface DelegateRebateVaultLog {
  rebateVault: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegateRebateVaultParams {
}

export interface DelegateTokenVaultLog {
  tokenVault: PublicKey;
  commitFrequency: number;
  validator: PublicKey;
}

export interface DelegateTokenVaultParams {
}

export interface DepositDirectBaseLog {
  owner: PublicKey;
  depositor: PublicKey;
  tokenMint: PublicKey;
  amount: BN;
}

export interface DepositDirectParams {
  amount: BN;
}

export interface DepositEntry {
  mint: PublicKey;
  amount: BN;
}

export interface DepositStakeLog {
  poolName: string;
  owner: PublicKey;
  lpTokens: BN;
}

export interface DepositTokenStakeErLog {
  owner: PublicKey;
  depositAmount: BN;
  activeStakeAmount: BN;
  level: number;
  credited: boolean;
}

export interface DepositTokenStakeLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  depositAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
}

export interface DepositTokenStakeLogV2 {
  owner: PublicKey;
  tokenStake: PublicKey;
  depositAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface DepositTokenStakeSettleBaseLog {
  owner: PublicKey;
  depositAmount: BN;
  credited: boolean;
  amountRefunded: BN;
}

export interface DepositTokenStakeWithActionBaseLog {
  owner: PublicKey;
  depositAmount: BN;
}

export interface DepositTokenStakeWithActionParams {
  depositAmount: BN;
}

export interface DistributeTokenRewardLog {
  amount: BN;
  epochCount: number;
  padding: BN[];
}

export interface DistributeTokenRewardParams {
  amount: BN;
  epochCount: number;
}

export interface EditLimitOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  reserveUsd: BN;
  stopLossPrice: BN;
  stopLossPriceExponent: number;
  takeProfitPrice: BN;
  takeProfitPriceExponent: number;
  receiveCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface EditLimitOrderErParams {
  orderId: number;
  limitPrice: OraclePrice;
  sizeAmount: BN;
  stopLossPrice: OraclePrice;
  takeProfitPrice: OraclePrice;
}

export interface EditLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  reserveUsd: BN;
  stopLossPrice: BN;
  stopLossPriceExponent: number;
  takeProfitPrice: BN;
  takeProfitPriceExponent: number;
  receiveCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface EditTriggerOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  receiveCustodyUid: number;
  isStopLoss: boolean;
}

export interface EditTriggerOrderErParams {
  orderId: number;
  triggerPrice: OraclePrice;
  deltaSizeAmount: BN;
  isStopLoss: boolean;
}

export interface EditTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  receiveCustodyUid: number;
  isStopLoss: boolean;
}

export interface ExecuteLimitOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
  reserveCustodyUid: number;
  padding: BN[];
}

export interface ExecuteLimitOrderErParams {
  orderId: number;
  privilege: Privilege;
}

export interface ExecuteLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
}

export interface ExecuteLimitOrderLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
  padding: BN[];
}

export interface ExecuteLimitOrderLogV2 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
  entryFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
  feeRebateUsdAmount: BN;
  padding: BN[];
}

export interface ExecuteLimitWithSwapLog {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
  reserveCustodyUid: BN;
  reserveAmount: BN;
  swapFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
}

export interface ExecuteLimitWithSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  reserveCustodyUid: number;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  deltaCollateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
  padding: BN[];
}

export interface ExecuteLimitWithSwapLogV2 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
  entryFeeAmount: BN;
  reserveCustodyUid: BN;
  reserveAmount: BN;
  swapFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  limitPrice: BN;
  limitPriceExponent: number;
  feeRebateAmount: BN;
  padding: BN[];
}

export interface ExecuteTriggerOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  outputCustodyUid: number;
  outAmount: BN;
  isStopLoss: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  triggerPrice: BN;
  triggerPriceExponent: number;
  priceImpactUsd: BN;
  deltaLockedAmount: BN;
  padding: BN[];
}

export interface ExecuteTriggerOrderErParams {
  isStopLoss: boolean;
  orderId: number;
  privilege: Privilege;
}

export interface ExecuteTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  exitFeeAmount: BN;
  isStopLoss: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  triggerPrice: BN;
  triggerPriceExponent: number;
}

export interface ExecuteTriggerOrderLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  outAmount: BN;
  isStopLoss: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  triggerPrice: BN;
  triggerPriceExponent: number;
  priceImpactUsd: BN;
  deltaLockedAmount: BN;
  padding: BN[];
}

export interface ExecuteTriggerWithSwapLog {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  exitFeeAmount: BN;
  isStopLoss: boolean;
  receiveCustodyUid: BN;
  receiveAmount: BN;
  swapFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  triggerPrice: BN;
  triggerPriceExponent: number;
}

export interface ExecuteTriggerWithSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  exitFeeUsd: BN;
  outCustodyUid: number;
  outAmount: BN;
  isStopLoss: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  triggerPrice: BN;
  triggerPriceExponent: number;
  priceImpactUsd: BN;
  deltaLockedAmount: BN;
  padding: BN[];
}

export interface Fees {
  mode: FeesMode;
  swapIn: RatioFees;
  swapOut: RatioFees;
  stableSwapIn: RatioFees;
  stableSwapOut: RatioFees;
  addLiquidity: RatioFees;
  removeLiquidity: RatioFees;
  openPosition: BN;
  closePosition: BN;
  volatility: BN;
}

export type FeesMode =
  { fixed: Record<string, never> }
  | { linear: Record<string, never> };

export interface FeesStats {
  accrued: BN;
  distributed: BN;
  paid: BN;
  rewardPerLpStaked: BN;
  protocolFee: BN;
}

export interface FlpStake {
  owner: PublicKey;
  pool: PublicKey;
  stakeStats: StakeStats;
  rewardSnapshot: BN;
  unclaimedRewards: BN;
  feeShareBps: BN;
  isInitialized: number;
  bump: number;
}

export interface ForceCloseOrderErLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  orderId: number;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  reserveAmount: BN;
  padding: BN[];
}

export interface ForceCloseOrderErParams {
}

export interface ForceClosePositionErLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  lockedAmount: BN;
  outputAmount: BN;
  outputCustodyUid: number;
  padding: BN[];
}

export interface ForceClosePositionErParams {
}

export interface ForceCloseTriggerOrderErLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  triggerOrdersCancelled: number;
  padding: BN[];
}

export interface ForceSettleOrderLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  orderId: number;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  reserveAmount: BN;
  padding: BN[];
}

export interface ForceSettlePositionLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  priceImpactUsd: BN;
  lockedAmount: BN;
  padding: BN[];
}

export interface ForceSettleTriggerOrderLog {
  admin: PublicKey;
  owner: PublicKey;
  market: PublicKey;
  triggerOrdersCancelled: number;
  padding: BN[];
}

export interface GetAddCollateralQuoteErParams {
  amountIn: BN;
}

export interface GetAddCollateralQuoteParams {
  amountIn: BN;
}

export interface GetAddCompoundingLiquidityAmountAndFeeParams {
  amountIn: BN;
}

export interface GetAddLiquidityAmountAndFeeParams {
  amountIn: BN;
}

export interface GetAssetsUnderManagementParams {
}

export interface GetClosePositionQuoteErParams {
  sizeDeltaUsd: BN;
  privilege: Privilege;
  discountIndex: (number | null);
  triggerPrice: (OraclePrice | null);
}

export interface GetClosePositionQuoteParams {
  sizeDeltaUsd: BN;
  privilege: Privilege;
  discountIndex: (number | null);
  triggerPrice: (OraclePrice | null);
}

export interface GetCompoundingTokenDataParams {
}

export interface GetCompoundingTokenPriceParams {
}

export interface GetEntryPriceAndFeeErParams {
  collateral: BN;
  size: BN;
  side: Side;
}

export interface GetEntryPriceAndFeeParams {
  collateral: BN;
  size: BN;
  side: Side;
}

export interface GetExitPriceAndFeeErParams {
}

export interface GetExitPriceAndFeeParams {
}

export interface GetLiquidationPriceErParams {
}

export interface GetLiquidationPriceParams {
}

export interface GetLiquidationStateErParams {
}

export interface GetLiquidationStateParams {
}

export interface GetLpTokenPriceParams {
}

export interface GetOpenPositionQuoteErParams {
  amountIn: BN;
  leverage: BN;
  privilege: Privilege;
  discountIndex: (number | null);
  limitPrice: (OraclePrice | null);
  takeProfitPrice: (OraclePrice | null);
  stopLossPrice: (OraclePrice | null);
}

export interface GetOpenPositionQuoteParams {
  amountIn: BN;
  leverage: BN;
  privilege: Privilege;
  discountIndex: (number | null);
  limitPrice: (OraclePrice | null);
  takeProfitPrice: (OraclePrice | null);
  stopLossPrice: (OraclePrice | null);
}

export interface GetOraclePriceErParams {
}

export interface GetOraclePriceParams {
}

export interface GetPnlErParams {
}

export interface GetPnlParams {
}

export interface GetPositionDataErParams {
}

export interface GetPositionDataParams {
}

export interface GetRemoveCollateralQuoteErParams {
  collateralDeltaUsd: BN;
}

export interface GetRemoveCollateralQuoteParams {
  collateralDeltaUsd: BN;
}

export interface GetRemoveCompoundingLiquidityAmountAndFeeParams {
  compoundingAmountIn: BN;
}

export interface GetRemoveLiquidityAmountAndFeeParams {
  lpAmountIn: BN;
}

export interface GetSwapAmountAndFeesParams {
  amountIn: BN;
}

export interface IncreasePositionSizeErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  inputAmount: BN;
  deltaCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  finalCollateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  isDegen: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface IncreasePositionSizeErParams {
  priceWithSlippage: OraclePrice;
  sizeDelta: BN;
  deltaCollateralAmount: BN;
  privilege: Privilege;
}

export interface IncreaseSizeLog {
  owner: PublicKey;
  market: PublicKey;
  priceUsd: BN;
  sizeAmount: BN;
  sizeUsd: BN;
  feeAmount: BN;
}

export interface IncreaseSizeLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  finalCollateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  isDegen: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface IncreaseSizeLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  feeAmount: BN;
}

export interface IncreaseSizeLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  finalCollateralAmount: BN;
  finalCollateralUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface IncreaseSizeLogV4 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  deltaSizeAmount: BN;
  deltaSizeUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  finalCollateralAmount: BN;
  finalCollateralUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  entryFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  isDegen: boolean;
  padding: number[];
}

export interface InitBasketParams {
  positionCapacity: number;
  orderCapacity: number;
  ledgerCapacity: number;
  orderItemCapacity: number;
}

export interface InitCompoundingParams {
  feeShareBps: BN;
  metadataTitle: string;
  metadataSymbol: string;
  metadataUri: string;
}

export interface InitCustodyAccountParams {
  poolName: string;
  poolBump: number;
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  token22: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  tokenAmountMultiplier: BN;
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
  uid: number;
}

export interface InitDelegateTokenStakeEvent {
  owner: PublicKey;
  tokenStake: PublicKey;
}

export interface InitMarketAccountParams {
  poolName: string;
  poolBump: number;
  targetCustodyMint: PublicKey;
  targetCustodyBump: number;
  collateralCustodyMint: PublicKey;
  collateralCustodyBump: number;
  side: Side;
  correlation: boolean;
  maxPayoffBps: BN;
  permissions: MarketPermissions;
}

export interface InitParams {
  minSignatures: number;
  permissions: Permissions;
  voltageMultiplier: VoltageMultiplier;
  tradingDiscount: BN[];
  referralRebate: BN[];
  defaultRebate: BN;
}

export interface InitReallocVaultParams {
  fundingLamports: BN;
}

export interface InitRebateVaultParams {
  allowRebatePayout: boolean;
}

export interface InitRevenueTokenAccountParams {
  feeShareBps: BN;
}

export interface InitStakingParams {
  stakingFeeShareBps: BN;
}

export interface InitTokenVaultParams {
  tokenPermissions: TokenPermissions;
  amount: BN;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  stakeLevel: BN[];
}

export interface InitUserDepositLedgerParams {
  depositCapacity: number;
}

export interface InternalEmaPrice {
  emaPrice: BN;
  publishTime: BN;
}

export interface InternalPrice {
  price: BN;
  conf: BN;
  publishTime: BN;
}

export interface Ledger {
  mint: PublicKey;
  amount: BN;
}

export interface LimitOrder {
  limitPrice: OraclePrice;
  reserveAmount: BN;
  reserveCustodyUid: number;
  receiveCustodyUid: number;
  sizeAmount: BN;
  stopLossPrice: OraclePrice;
  takeProfitPrice: OraclePrice;
}

export interface LiquidateLog {
  owner: PublicKey;
  market: PublicKey;
  priceUsd: BN;
  sizeUsd: BN;
  sizeAmount: BN;
  feeAmount: BN;
}

export interface LiquidateLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  penaltyUsd: BN;
  exitFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface LiquidateLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeUsd: BN;
  sizeAmount: BN;
  feeAmount: BN;
}

export interface LiquidateLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  exitFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface LiquidatePositionErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  duration: BN;
  exitPrice: BN;
  exitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  penaltyUsd: BN;
  exitFeeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface LiquidatePositionErParams {
}

export interface Market {
  pool: PublicKey;
  targetCustody: PublicKey;
  collateralCustody: PublicKey;
  side: Side;
  correlation: boolean;
  maxPayoffBps: BN;
  permissions: MarketPermissions;
  degenExposureUsd: BN;
  collectivePosition: PositionStats;
  targetCustodyUid: number;
  padding: number[];
  collateralCustodyUid: number;
  padding2: number[];
  bump: number;
}

export interface MarketPermissions {
  allowOpenPosition: boolean;
  allowClosePosition: boolean;
  allowCollateralWithdrawal: boolean;
  allowSizeChange: boolean;
}

export interface MigrateFlpErLog {
  poolName: string;
  owner: PublicKey;
  compoundingTokenAmount: BN;
  lpAmountOut: BN;
  rewardLpAmount: BN;
  rewardPerLpStaked: BN;
  lpPriceUsd: BN;
  slippageOk: boolean;
}

export interface MigrateFlpLog {
  poolName: string;
  owner: PublicKey;
  amount: BN;
  lpAmountOut: BN;
  rewardLpAmount: BN;
  rewardPerLpStaked: BN;
  lpPriceUsd: BN;
  compoundingPriceUsd: BN;
}

export interface MigrateFlpReceipt {
  pool: PublicKey;
  owner: PublicKey;
  compoundingTokenAccount: PublicKey;
  compoundingTokenAmount: BN;
  lpAmountOut: BN;
  rewardLpAmount: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface MigrateFlpSettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  compoundingTokenAmount: BN;
  lpAmountOut: BN;
  rewardLpAmount: BN;
}

export interface MigrateFlpWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  compoundingTokenAmount: BN;
}

export interface MigrateFlpWithActionParams {
  compoundingTokenAmount: BN;
  queueErAction: boolean;
}

export interface MigrateMarketOrderParams {
}

export interface MigrateMarketPositionLog {
  owner: PublicKey;
  market: PublicKey;
  position: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
}

export interface MigrateMarketPositionParams {
}

export interface MigrateOrderToBasketErParams {
}

export interface MigratePoolLpSupplyLog {
  poolName: string;
  lpSupply: BN;
}

export interface MigratePoolLpSupplyParams {
  poolName: string;
  poolBump: number;
}

export interface MigratePositionLog {
  owner: PublicKey;
  market: PublicKey;
  position: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
}

export interface MigratePositionToBasketErParams {
}

export interface MigrateStakeErLog {
  poolName: string;
  owner: PublicKey;
  amount: BN;
  compoundingAmountOut: BN;
  poolRewardLpAmount: BN;
  rewardPerLpStaked: BN;
  lpPriceUsd: BN;
  slippageOk: boolean;
}

export interface MigrateStakeLog {
  poolName: string;
  owner: PublicKey;
  amount: BN;
  compoundingAmountOut: BN;
  poolLpAmount: BN;
  rewardPerLpStaked: BN;
  lpPriceUsd: BN;
  compoundingPriceUsd: BN;
}

export interface MigrateStakeReceipt {
  pool: PublicKey;
  owner: PublicKey;
  compoundingTokenAccount: PublicKey;
  amount: BN;
  compoundingAmountOut: BN;
  poolRewardLpAmount: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface MigrateStakeSettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  amount: BN;
  compoundingAmountOut: BN;
  poolRewardLpAmount: BN;
}

export interface MigrateStakeWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  amount: BN;
}

export interface MigrateStakeWithActionParams {
  amount: BN;
  queueErAction: boolean;
}

export interface MoveProtocolFeesErLog {
  poolName: string;
  keeper: PublicKey;
  protocolFeeTotal: BN;
  revenueAmount: BN;
  protocolFeeAmount: BN;
}

export interface MoveProtocolFeesLog {
  poolName: string;
  revenueAmount: BN;
  protocolFee: BN;
  revenueFeeShare: BN;
  padding: BN[];
}

export interface MoveProtocolFeesReceipt {
  pool: PublicKey;
  keeper: PublicKey;
  rewardCustodyTokenAccount: PublicKey;
  revenueAmount: BN;
  protocolFeeAmount: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface MoveProtocolFeesSettleBaseLog {
  pool: PublicKey;
  keeper: PublicKey;
  revenueAmount: BN;
  protocolFeeAmount: BN;
  feeShareBps: BN;
}

export interface MoveProtocolFeesWithActionBaseLog {
  poolName: string;
  keeper: PublicKey;
}

export interface MoveProtocolFeesWithActionParams {
}

export interface Multisig {
  numSigners: number;
  numSigned: number;
  minSignatures: number;
  instructionAccountsLen: number;
  instructionDataLen: number;
  instructionHash: BN;
  signers: PublicKey[];
  signed: number[];
  bump: number;
}

export interface NewPositionPricesAndFee {
  entryPrice: OraclePrice;
  feeUsd: BN;
}

export interface OpenPositionErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  inputCustodyUid: number;
  inputPrice: BN;
  inputPriceExponent: number;
  inputAmount: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  isDegen: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface OpenPositionErParams {
  priceWithSlippage: OraclePrice;
  collateralAmount: BN;
  sizeAmount: BN;
  privilege: Privilege;
}

export interface OpenPositionLog {
  owner: PublicKey;
  market: PublicKey;
  priceUsd: BN;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
}

export interface OpenPositionLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  inputAmount: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  isDegen: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface OpenPositionLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
}

export interface OpenPositionLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface OpenPositionLogV4 {
  owner: PublicKey;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  feeAmount: BN;
  feeRebateAmount: BN;
  entryFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  isDegen: boolean;
  padding: number[];
}

export interface OpenPositionQuoteData {
  amountIn: BN;
  swapRequired: boolean;
  collateralAmount: BN;
  collateralUsd: BN;
  sizeAmount: BN;
  sizeUsd: BN;
  entryPrice: OraclePrice;
  liquidationPrice: OraclePrice;
  entryFeeUsd: BN;
  entryFeeBeforeDiscountUsd: BN;
  volatilityFeeUsd: BN;
  totalFeeUsd: BN;
  feeRate: BN;
  leverage: BN;
  availableLiquidityUsd: BN;
  borrowFeeRate: BN;
  hasExistingPosition: boolean;
  oldLeverage: BN;
  oldEntryPrice: OraclePrice;
  oldLiquidationPrice: OraclePrice;
  finalLeverage: BN;
  finalEntryPrice: OraclePrice;
  finalLiquidationPrice: OraclePrice;
  takeProfitQuote: TriggerQuote;
  stopLossQuote: TriggerQuote;
}

export interface OracleParams {
  intOracleAccount: PublicKey;
  extOracleAccount: PublicKey;
  oracleType: OracleType;
  maxDivergenceBps: BN;
  maxConfBps: BN;
  maxPriceAgeSec: number;
  maxBackupAgeSec: number;
}

export interface OraclePrice {
  price: BN;
  exponent: number;
}

export type OracleType =
  { none: Record<string, never> }
  | { custom: Record<string, never> }
  | { pyth: Record<string, never> };

export interface Order {
  owner: PublicKey;
  market: PublicKey;
  limitOrders: LimitOrder[];
  takeProfitOrders: TriggerOrder[];
  stopLossOrders: TriggerOrder[];
  isInitialised: boolean;
  isActive: boolean;
  openSl: number;
  openTp: number;
  inactiveSl: number;
  inactiveTp: number;
  activeOrders: number;
  bump: number;
  referenceTimestamp: BN;
  executionCount: BN;
  migrateFlag: boolean;
  padding: number[];
  paddingU64: BN[];
}

export interface OrderMeta {
  market: PublicKey;
  order: BasketOrder;
}

export interface Permissions {
  allowSwap: boolean;
  allowAddLiquidity: boolean;
  allowRemoveLiquidity: boolean;
  allowOpenPosition: boolean;
  allowClosePosition: boolean;
  allowCollateralWithdrawal: boolean;
  allowSizeChange: boolean;
  allowLiquidation: boolean;
  allowLpStaking: boolean;
  allowFeeDistribution: boolean;
  allowUngatedTrading: boolean;
  allowFeeDiscounts: boolean;
  allowReferralRebates: boolean;
}

export interface Perpetuals {
  permissions: Permissions;
  pools: PublicKey[];
  collections: PublicKey[];
  voltageMultiplier: VoltageMultiplier;
  tradingDiscount: BN[];
  referralRebate: BN[];
  defaultRebate: BN;
  inceptionTime: BN;
  transferAuthorityBump: number;
  perpetualsBump: number;
  tradeLimit: number;
  triggerOrderLimit: number;
  rebateLimitUsd: number;
}

export interface PlaceLimitOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  reserveUsd: BN;
  stopLossPrice: BN;
  stopLossPriceExponent: number;
  takeProfitPrice: BN;
  takeProfitPriceExponent: number;
  receiveCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface PlaceLimitOrderErParams {
  limitPrice: OraclePrice;
  reserveAmount: BN;
  sizeAmount: BN;
  stopLossPrice: OraclePrice;
  takeProfitPrice: OraclePrice;
}

export interface PlaceLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  limitPrice: BN;
  limitPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  reservePrice: BN;
  reservePriceExponent: number;
  reserveAmount: BN;
  reserveUsd: BN;
  stopLossPrice: BN;
  stopLossPriceExponent: number;
  takeProfitPrice: BN;
  takeProfitPriceExponent: number;
  receiveCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface PlaceTriggerOrderErLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  receiveCustodyUid: number;
  isStopLoss: boolean;
}

export interface PlaceTriggerOrderErParams {
  triggerPrice: OraclePrice;
  deltaSizeAmount: BN;
  isStopLoss: boolean;
}

export interface PlaceTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  priceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  receiveCustodyUid: number;
  isStopLoss: boolean;
}

export interface Pool {
  name: string;
  permissions: Permissions;
  inceptionTime: BN;
  lpMint: PublicKey;
  oracleAuthority: PublicKey;
  stakedLpVault: PublicKey;
  rewardCustody: PublicKey;
  custodies: PublicKey[];
  ratios: TokenRatios[];
  markets: PublicKey[];
  maxAumUsd: BN;
  buffer: BN;
  rawAumUsd: BN;
  equityUsd: BN;
  totalStaked: StakeStats;
  stakingFeeShareBps: BN;
  bump: number;
  lpMintBump: number;
  stakedLpVaultBump: number;
  vpVolumeFactor: number;
  uniqueCustodyCount: number;
  padding: number[];
  stakingFeeBoostBps: BN[];
  compoundingMint: PublicKey;
  compoundingLpVault: PublicKey;
  compoundingStats: CompoundingStats;
  compoundingMintBump: number;
  compoundingLpVaultBump: number;
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  lpPrice: BN;
  compoundingLpPrice: BN;
  lastUpdatedTimestamp: BN;
  feesObligationUsd: BN;
  rebateObligationUsd: BN;
  thresholdUsd: BN;
  lpSupply: BN;
}

export interface Position {
  owner: PublicKey;
  market: PublicKey;
  delegate: PublicKey;
  openTime: BN;
  updateTime: BN;
  entryPrice: OraclePrice;
  sizeAmount: BN;
  sizeUsd: BN;
  lockedAmount: BN;
  lockedUsd: BN;
  priceImpactUsd: BN;
  collateralUsd: BN;
  unsettledValueUsd: BN;
  unsettledFeesUsd: BN;
  cumulativeLockFeeSnapshot: BN;
  degenSizeUsd: BN;
  referencePrice: OraclePrice;
  isActive: boolean;
  buffer: number[];
  priceImpactSet: number;
  sizeDecimals: number;
  lockedDecimals: number;
  collateralDecimals: number;
  bump: number;
  migrateFlag: boolean;
  padding: number[];
}

export interface PositionData {
  entryOraclePrice: OraclePrice;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralAmount: BN;
  collateralUsd: BN;
  pnl: PositionPnl;
  pnlWithFeeUsd: BN;
  pnlPercentageWithFee: BN;
  pnlWithoutFeeUsd: BN;
  pnlPercentageWithoutFee: BN;
  leverage: BN;
  liquidationPrice: OraclePrice;
}

export interface PositionMeta {
  market: PublicKey;
  position: Position;
}

export interface PositionPnl {
  profitUsd: BN;
  lossUsd: BN;
  exitFeeUsd: BN;
  borrowFeeUsd: BN;
  exitFeeAmount: BN;
  borrowFeeAmount: BN;
  priceImpactUsd: BN;
  priceImpactSet: boolean;
}

export interface PositionStats {
  openPositions: BN;
  updateTime: BN;
  averageEntryPrice: OraclePrice;
  sizeAmount: BN;
  sizeUsd: BN;
  lockedAmount: BN;
  lockedUsd: BN;
  collateralAmount: BN;
  collateralLiabilityUsd: BN;
  unsettledFeeUsd: BN;
  cumulativeLockFeeSnapshot: BN;
  sizeDecimals: number;
  lockedDecimals: number;
  collateralDecimals: number;
}

export interface PriceAndFee {
  price: OraclePrice;
  feeUsd: BN;
}

export interface PricingParams {
  tradeSpreadMin: BN;
  tradeSpreadMax: BN;
  swapSpread: BN;
  minInitLeverage: number;
  minInitDegenLeverage: number;
  maxInitLeverage: number;
  maxInitDegenLeverage: number;
  maxLeverage: number;
  maxDegenLeverage: number;
  minCollateralUsd: number;
  minDegenCollateralUsd: number;
  delaySeconds: BN;
  maxUtilization: number;
  degenPositionFactor: number;
  degenExposureFactor: number;
  maxPositionSizeUsd: BN;
  maxExposureUsd: BN;
}

export type Privilege =
  { none: Record<string, never> }
  | { stake: Record<string, never> }
  | { referral: Record<string, never> };

export interface ProfitAndLoss {
  profit: BN;
  loss: BN;
}

export interface ProtocolVault {
  key: PublicKey;
  tokenAccount: PublicKey;
  isInitialized: boolean;
  bump: number;
  tokenAccountBump: number;
  feeShareBps: BN;
  feeAmount: BN;
  padding: BN[];
}

export interface RatioFees {
  minFee: BN;
  targetFee: BN;
  maxFee: BN;
}

export interface ReallocVault {
  bump: number;
  padding: number[];
}

export interface RebateVault {
  key: PublicKey;
  tokenAccount: PublicKey;
  isInitialized: boolean;
  allowPayout: boolean;
  bump: number;
  tokenAccountBump: number;
  availableUsd: BN;
  availableAmount: BN;
  padding: BN[];
}

export interface Referral {
  isInitialized: boolean;
  bump: number;
  refererTokenStakeAccount: PublicKey;
  refererBoosterAccount: PublicKey;
  padding: BN[];
}

export interface ReferralRebateLog {
  tokenStake: PublicKey;
  owner: PublicKey;
  rebateUsd: BN;
  volumeUsd: BN;
  voltagePointsType: number;
  blockedRebateUsd: BN;
  padding: BN[];
}

export interface RefreshStakeErLog {
  poolName: string;
  rewardPerLpStaked: BN;
  processed: number;
  skipped: number;
}

export interface RefreshStakeLog {
  poolName: string;
  rewardPerLpStaked: BN;
}

export interface RefreshStakeUserErLog {
  owner: PublicKey;
  poolName: string;
  rewardAmount: BN;
  rewardMint: PublicKey;
  rewardShare: BN;
}

export interface RefreshStakeUserLog {
  owner: PublicKey;
  poolName: string;
  rewardAmount: BN;
  rewardMint: PublicKey;
  rewardShare: BN;
}

export interface RefreshTokenStakeErLog {
  revenuePerFafStaked: BN;
  processed: number;
  skipped: number;
}

export interface RefreshTokenStakeLog {
  revenuePerFafStaked: BN;
}

export interface RefreshTokenStakeUserErLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  revenueAmount: BN;
  newlyUnlockedAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface RefreshTokenStakeUserLog {
  owner: PublicKey;
  revenueAmount: BN;
  newlyUnlockedAmount: BN;
}

export interface RefreshTokenStakeUserLogV2 {
  owner: PublicKey;
  tokenStake: PublicKey;
  revenueAmount: BN;
  newlyUnlockedAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface ReimburseParams {
  amountIn: BN;
}

export interface RemoveCollateralAndSwapLog {
  owner: PublicKey;
  market: PublicKey;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  finalCollateralAmount: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  receiveCustodyUid: BN;
  receiveAmount: BN;
  swapFeeAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface RemoveCollateralAndSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  receiveCustodyUid: number;
  receiveAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface RemoveCollateralErLog {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  receiveAmount: BN;
  outputCustodyUid: number;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface RemoveCollateralErParams {
  collateralDeltaUsd: BN;
}

export interface RemoveCollateralLog {
  owner: PublicKey;
  market: PublicKey;
  collateralAmount: BN;
  collateralPriceUsd: BN;
}

export interface RemoveCollateralLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  receiveAmount: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface RemoveCollateralLogV2 {
  owner: PublicKey;
  market: PublicKey;
  collateralAmount: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
}

export interface RemoveCollateralLogV3 {
  owner: PublicKey;
  market: PublicKey;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  finalCollateralAmount: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface RemoveCollateralQuoteData {
  collateralDeltaUsd: BN;
  receiveTokenAmount: BN;
  receiveTokenAmountUsd: BN;
  existingCollateralUsd: BN;
  existingLeverage: BN;
  existingLiquidationPrice: OraclePrice;
  newCollateralUsd: BN;
  newLeverage: BN;
  newLiquidationPrice: OraclePrice;
  maxWithdrawableUsd: BN;
  swapRequired: boolean;
  swapPossible: boolean;
  passesMinCollateral: boolean;
  passesLeverageCheck: boolean;
}

export interface RemoveCompoundingLiquidityErLog {
  poolName: string;
  owner: PublicKey;
  outCustodyUid: BN;
  compoundingAmountIn: BN;
  rewardAmount: BN;
  outLpToRedeem: BN;
  outTokenAmount: BN;
  feeAmount: BN;
  compoundingPriceUsd: BN;
  tokenOutPrice: BN;
  tokenOutPriceExponent: number;
  slippageOk: boolean;
}

export interface RemoveCompoundingLiquidityLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  compoundingAmountIn: BN;
  amountOut: BN;
  feeAmount: BN;
  rewardPerLpStaked: BN;
  compoundingPriceUsd: BN;
  tokenOutPrice: BN;
  tokenOutPriceExponent: number;
}

export interface RemoveCompoundingLiquiditySettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  outCustodyId: number;
  amountOut: BN;
  compoundingReminted: BN;
  lpDiffMinted: BN;
  lpDiffBurnt: BN;
}

export interface RemoveCompoundingLiquidityWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  outCustodyUid: BN;
  rewardCustodyUid: BN;
  compoundingAmountIn: BN;
  minAmountOut: BN;
}

export interface RemoveCompoundingLiquidityWithActionParams {
  compoundingAmountIn: BN;
  minAmountOut: BN;
  queueErAction: boolean;
}

export interface RemoveCustodyErLog {
  pool: PublicKey;
  custody: PublicKey;
  mint: PublicKey;
}

export interface RemoveCustodyErParams {
  ratios: TokenRatios[];
}

export interface RemoveCustodyParams {
  ratios: TokenRatios[];
}

export interface RemoveCustodySettleBaseLog {
  pool: PublicKey;
  custody: PublicKey;
  residualAmount: BN;
}

export interface RemoveLiquidityErLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  lpAmountIn: BN;
  amountOut: BN;
  feeAmount: BN;
  lpPriceUsd: BN;
  userReward: BN;
  tokenOutPrice: BN;
  tokenOutPriceExponent: number;
  slippageOk: boolean;
}

export interface RemoveLiquidityLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  lpAmountIn: BN;
  amountOut: BN;
  feeAmount: BN;
}

export interface RemoveLiquidityLogV2 {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  lpAmountIn: BN;
  amountOut: BN;
  feeAmount: BN;
  lpPriceUsd: BN;
  tokenOutPrice: BN;
  tokenOutPriceExponent: number;
}

export interface RemoveLiquiditySettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  custodyId: number;
  lpBurnt: BN;
  amountOut: BN;
}

export interface RemoveLiquidityWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  custodyUid: BN;
  unstakeAmount: BN;
  minAmountOut: BN;
}

export interface RemoveLiquidityWithActionParams {
  unstakeAmount: BN;
  minAmountOut: BN;
  queueErAction: boolean;
}

export interface RemoveMarketErLog {
  pool: PublicKey;
  market: PublicKey;
  targetCustody: PublicKey;
  collateralCustody: PublicKey;
}

export interface RemoveMarketParams {
}

export interface RemoveMarketSettleBaseLog {
  market: PublicKey;
  targetCustody: PublicKey;
  collateralCustody: PublicKey;
}

export interface RemovePoolParams {
}

export interface RenameFlpParams {
  flag: BN;
  lpTokenName: string;
  lpTokenSymbol: string;
  lpTokenUri: string;
}

export interface ResizeInternalOracleParams {
  lazerFeedId: number;
}

export interface SessionTokenV2 {
  authority: PublicKey;
  targetProgram: PublicKey;
  sessionSigner: PublicKey;
  feePayer: PublicKey;
  validUntil: BN;
}

export interface SetAdminSignersParams {
  minSignatures: number;
}

export interface SetCustodyConfigErLog {
  pool: PublicKey;
  custody: PublicKey;
  admin: PublicKey;
}

export interface SetCustodyConfigErParams {
  isVirtual: boolean;
  depegAdjustment: boolean;
  inversePrice: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  ratios: TokenRatios[];
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
  token22: boolean;
}

export interface SetCustodyConfigParams {
  isVirtual: boolean;
  depegAdjustment: boolean;
  inversePrice: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  ratios: TokenRatios[];
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
  token22: boolean;
}

export interface SetCustodyTokenMultiplierErLog {
  custody: PublicKey;
  admin: PublicKey;
  tokenAmountMultiplier: BN;
}

export interface SetCustodyTokenMultiplierErParams {
}

export interface SetCustodyTokenMultiplierParams {
}

export interface SetCustomOraclePriceParams {
  price: BN;
  expo: number;
  conf: BN;
  ema: BN;
  publishTime: BN;
}

export interface SetFeeShareParams {
  feeShareBps: BN;
}

export interface SetInternalAccountConfigErLog {
  admin: PublicKey;
  custodyTokenMint: PublicKey;
  intOracleAccount: PublicKey;
  lazerFeedId: number;
}

export interface SetInternalAccountConfigErParams {
  lazerFeedId: number;
}

export interface SetInternalCurrentPriceErParams {
  useCurrentTime: number;
  prices: InternalPrice[];
}

export interface SetInternalCurrentPriceParams {
  useCurrentTime: number;
  prices: InternalPrice[];
}

export interface SetInternalEmaPriceErParams {
  prices: InternalEmaPrice[];
}

export interface SetInternalEmaPriceParams {
  prices: InternalEmaPrice[];
}

export interface SetInternalLazerPriceErParams {
  messageData: Buffer;
}

export interface SetInternalLazerPriceParams {
  messageData: Buffer;
}

export interface SetLpTokenPriceErLog {
  pool: PublicKey;
  lpPrice: BN;
  compoundingLpPrice: BN;
}

export interface SetLpTokenPriceErParams {
}

export interface SetMarketConfigErLog {
  market: PublicKey;
  admin: PublicKey;
}

export interface SetMarketConfigErParams {
  maxPayoffBps: BN;
  permissions: MarketPermissions;
  correlation: boolean;
}

export interface SetMarketConfigParams {
  maxPayoffBps: BN;
  permissions: MarketPermissions;
  correlation: boolean;
}

export interface SetPermissionsParams {
  permissions: Permissions;
}

export interface SetPerpetualsConfigParams {
  allowUngatedTrading: boolean;
  tradingDiscount: BN[];
  referralRebate: BN[];
  defaultRebate: BN;
  voltageMultiplier: VoltageMultiplier;
  tradeLimit: number;
  triggerOrderLimit: number;
  rebateLimitUsd: number;
}

export interface SetPoolConfigErLog {
  pool: PublicKey;
  admin: PublicKey;
}

export interface SetPoolConfigErParams {
  permissions: Permissions;
  oracleAuthority: PublicKey;
  maxAumUsd: BN;
  stakingFeeShareBps: BN;
  vpVolumeFactor: number;
  stakingFeeBoostBps: BN[];
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  thresholdUsd: BN;
}

export interface SetPoolConfigParams {
  permissions: Permissions;
  oracleAuthority: PublicKey;
  maxAumUsd: BN;
  stakingFeeShareBps: BN;
  vpVolumeFactor: number;
  stakingFeeBoostBps: BN[];
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  thresholdUsd: BN;
}

export interface SetPositionPriceImpactLog {
  position: PublicKey;
  market: PublicKey;
  priceImpactUsd: BN;
  padding: BN[];
}

export interface SetPositionPriceImpactParams {
  priceImpactUsd: BN;
}

export interface SetProtocolFeeShareParams {
  feeShareBps: BN;
}

export interface SetTestTimeParams {
  time: BN;
}

export interface SetTokenRewardLog {
  tokenStake: PublicKey;
  amount: BN;
  epochCount: number;
  padding: BN[];
}

export interface SetTokenRewardParams {
  amount: BN;
  epochCount: number;
}

export interface SetTokenStakeLevelErLog {
  admin: PublicKey;
  owner: PublicKey;
  level: number;
}

export interface SetTokenStakeLevelErParams {
  level: number;
  rebateRate: BN;
  maxRebateUsd: BN;
}

export interface SetTokenStakeLevelParams {
  level: number;
  rebateRate: BN;
  maxRebateUsd: BN;
}

export interface SetTokenVaultConfigErLog {
  admin: PublicKey;
}

export interface SetTokenVaultConfigErParams {
  tokenPermissions: TokenPermissions;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  stakeLevel: BN[];
  unlockPeriod: BN;
}

export interface SetTokenVaultConfigParams {
  tokenPermissions: TokenPermissions;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  stakeLevel: BN[];
  unlockPeriod: BN;
  allowRevenueDistribution: number;
}

export interface SetWhitelistConfigParams {
  isSwapFeeExempt: boolean;
  isDepositFeeExempt: boolean;
  isWithdrawalFeeExempt: boolean;
  poolAddress: PublicKey;
}

export interface SettleRebatesErLog {
  poolName: string;
  keeper: PublicKey;
  requiredUsd: BN;
  rebateUsd: BN;
  rebateAmount: BN;
}

export interface SettleRebatesLog {
  poolName: string;
  rebateUsd: BN;
  rebateAmount: BN;
  padding: BN[];
}

export interface SettleRebatesReceipt {
  pool: PublicKey;
  keeper: PublicKey;
  rebateAmount: BN;
  rebateUsd: BN;
  bump: number;
  processed: number;
  padding: number[];
}

export interface SettleRebatesSettleBaseLog {
  pool: PublicKey;
  keeper: PublicKey;
  rebateAmount: BN;
  rebateUsd: BN;
}

export interface SettleRebatesWithActionBaseLog {
  poolName: string;
  keeper: PublicKey;
}

export interface SettleRebatesWithActionParams {
}

export type Side =
  { none: Record<string, never> }
  | { long: Record<string, never> }
  | { short: Record<string, never> };

export interface StakeStats {
  pendingActivation: BN;
  activeAmount: BN;
  pendingDeactivation: BN;
  deactivatedAmount: BN;
}

export interface StakingDepositReceipt {
  pool: PublicKey;
  liquidityProvider: PublicKey;
  inTokenMint: PublicKey;
  amountIn: BN;
  minLpAmountOut: BN;
  lpTokensToMint: BN;
  feeAmount: BN;
  inCustodyId: number;
  bump: number;
  processed: number;
  padding: number[];
}

export interface StakingWithdrawReceipt {
  pool: PublicKey;
  liquidityProvider: PublicKey;
  tokenMint: PublicKey;
  custodyTokenAccount: PublicKey;
  lpTokensBurnt: BN;
  tokenAmountToWithdraw: BN;
  minTokenAmountOut: BN;
  feeAmount: BN;
  custodyId: number;
  bump: number;
  processed: number;
  padding: number[];
}

export interface SwapAmountAndFees {
  amountOut: BN;
  feeIn: BN;
  feeOut: BN;
}

export interface SwapAndAddCollateralLog {
  owner: PublicKey;
  market: PublicKey;
  receivingCustodyUid: BN;
  receiveAmount: BN;
  swapFeeAmount: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  deltaCollateralAmount: BN;
  finalCollateralAmount: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
}

export interface SwapAndAddCollateralLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  inputCustodyUid: number;
  inputPrice: BN;
  inputPriceExponent: number;
  deltaInputAmount: BN;
  deltaCollateralUsd: BN;
  finalCollateralUsd: BN;
  finalSizeAmount: BN;
  finalSizeUsd: BN;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface SwapAndOpenLog {
  poolName: string;
  owner: PublicKey;
  receivingCustodyUid: BN;
  collateralCustodyUid: BN;
  targetCustodyUid: BN;
  amountIn: BN;
  swapAmountOut: BN;
  swapFeeAmount: BN;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  collateralUsd: BN;
  positionFeeAmount: BN;
  feeRebateAmount: BN;
  receivingOracleAccountTime: BN;
  receivingOracleAccountType: number;
  receivingOracleAccountPrice: BN;
  receivingOracleAccountPriceExponent: number;
  collateralOracleAccountTime: BN;
  collateralOracleAccountType: number;
  collateralOracleAccountPrice: BN;
  collateralOracleAccountPriceExponent: number;
  targetOracleAccountTime: BN;
  targetOracleAccountType: number;
  targetOracleAccountPrice: BN;
  targetOracleAccountPriceExponent: number;
}

export interface SwapAndOpenLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  tradeId: BN;
  inputCustodyUid: number;
  inputPrice: BN;
  inputPriceExponent: number;
  inputAmount: BN;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralUsd: BN;
  feeUsd: BN;
  rebateUsd: BN;
  discountUsd: BN;
  entryFeeUsd: BN;
  isDegen: boolean;
  oracleAccountTime: BN;
  oracleAccountType: number;
  oracleAccountPrice: BN;
  oracleAccountPriceExponent: number;
  padding: BN[];
}

export interface SwapAndOpenLogV2 {
  poolName: string;
  owner: PublicKey;
  receivingCustodyUid: BN;
  collateralCustodyUid: BN;
  targetCustodyUid: BN;
  amountIn: BN;
  swapAmountOut: BN;
  swapFeeAmount: BN;
  market: PublicKey;
  entryPrice: BN;
  entryPriceExponent: number;
  sizeAmount: BN;
  sizeUsd: BN;
  collateralPrice: BN;
  collateralPriceExponent: number;
  collateralAmount: BN;
  collateralUsd: BN;
  positionFeeAmount: BN;
  feeRebateAmount: BN;
  entryFeeAmount: BN;
  receivingOracleAccountTime: BN;
  receivingOracleAccountType: number;
  receivingOracleAccountPrice: BN;
  receivingOracleAccountPriceExponent: number;
  collateralOracleAccountTime: BN;
  collateralOracleAccountType: number;
  collateralOracleAccountPrice: BN;
  collateralOracleAccountPriceExponent: number;
  targetOracleAccountTime: BN;
  targetOracleAccountType: number;
  targetOracleAccountPrice: BN;
  targetOracleAccountPriceExponent: number;
  isDegen: boolean;
  padding: number[];
}

export interface SwapErLog {
  poolName: string;
  owner: PublicKey;
  inCustodyUid: BN;
  outCustodyUid: BN;
  amountIn: BN;
  amountOut: BN;
  feeInAmount: BN;
  feeOutAmount: BN;
  slippageOk: boolean;
}

export interface SwapFeeInternalErLog {
  poolName: string;
  payer: PublicKey;
  feeAmount: BN;
  padding: BN[];
}

export interface SwapFeeInternalErParams {
}

export interface SwapFeeInternalLog {
  poolName: string;
  owner: PublicKey;
  custodyInUid: BN;
  custodyOutUid: BN;
  swapAmount: BN;
  rewardCustodyAmount: BN;
}

export interface SwapFeeInternalLogV2 {
  poolName: string;
  owner: PublicKey;
  custodyInUid: BN;
  custodyOutUid: BN;
  swapAmount: BN;
  rewardCustodyAmount: BN;
  inOracleAccountTime: BN;
  inOracleAccountType: number;
  inOracleAccountPrice: BN;
  inOracleAccountPriceExponent: number;
  outOracleAccountTime: BN;
  outOracleAccountType: number;
  outOracleAccountPrice: BN;
  outOracleAccountPriceExponent: number;
}

export interface SwapFeeInternalLogV3 {
  poolName: string;
  owner: PublicKey;
  feeAmount: BN;
  padding: BN[];
}

export interface SwapFeeInternalParams {
}

export interface SwapLog {
  poolName: string;
  owner: PublicKey;
  custodyInUid: BN;
  custodyOutUid: BN;
  amountIn: BN;
  amountOut: BN;
  feeInAmount: BN;
  feeOutAmount: BN;
}

export interface SwapLogV2 {
  poolName: string;
  owner: PublicKey;
  custodyInUid: BN;
  custodyOutUid: BN;
  amountIn: BN;
  amountOut: BN;
  feeInAmount: BN;
  feeOutAmount: BN;
  inOracleAccountTime: BN;
  inOracleAccountType: number;
  inOracleAccountPrice: BN;
  inOracleAccountPriceExponent: number;
  outOracleAccountTime: BN;
  outOracleAccountType: number;
  outOracleAccountPrice: BN;
  outOracleAccountPriceExponent: number;
}

export interface SwapReceipt {
  pool: PublicKey;
  owner: PublicKey;
  inAccount: PublicKey;
  outAccount: PublicKey;
  inMint: PublicKey;
  outMint: PublicKey;
  amountIn: BN;
  minAmountOut: BN;
  amountOut: BN;
  feeIn: BN;
  feeOut: BN;
  inCustodyId: number;
  outCustodyId: number;
  bump: number;
  processed: number;
  padding: number[];
}

export interface SwapSettleBaseLog {
  owner: PublicKey;
  pool: PublicKey;
  inCustodyId: number;
  outCustodyId: number;
  amountIn: BN;
  amountOut: BN;
  feeIn: BN;
  feeOut: BN;
}

export interface SwapWithActionBaseLog {
  poolName: string;
  owner: PublicKey;
  inCustodyUid: BN;
  outCustodyUid: BN;
  amountIn: BN;
  minAmountOut: BN;
}

export interface SwapWithActionParams {
  amountIn: BN;
  minAmountOut: BN;
  queueErAction: boolean;
}

export interface TestInitParams {
  minSignatures: number;
  permissions: Permissions;
}

export interface TokenPermissions {
  allowDeposits: boolean;
  allowWithdrawal: boolean;
  allowRewardWithdrawal: boolean;
}

export interface TokenRatios {
  target: BN;
  min: BN;
  max: BN;
}

export interface TokenStake {
  owner: PublicKey;
  isInitialized: boolean;
  bump: number;
  level: number;
  withdrawRequestCount: number;
  withdrawRequest: WithdrawRequest[];
  rebateRate: BN;
  activeStakeAmount: BN;
  updateTimestamp: BN;
  tradeTimestamp: BN;
  tradeCounter: number;
  lastRewardEpochCount: number;
  rewardTokens: BN;
  unclaimedRevenueAmount: BN;
  revenueSnapshot: BN;
  claimableRebateUsd: BN;
  rebateUsdSnapshot: BN;
  rebateDayTimestamp: BN;
  maxRebateUsd: BN;
  padding: BN[];
}

export interface TokenStakeDepositReceipt {
  owner: PublicKey;
  tokenMint: PublicKey;
  depositAmount: BN;
  bump: number;
  processed: number;
  credited: number;
  padding: number[];
}

export interface TokenStakeStats {
  lockedAmount: BN;
  activeAmount: BN;
  withdrawableAmount: BN;
  buffer: BN;
}

export interface TokenVault {
  isInitialized: boolean;
  bump: number;
  tokenAccountBump: number;
  tokenMint: PublicKey;
  tokenVaultTokenAccount: PublicKey;
  tokenPermissions: TokenPermissions;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  withdrawInstantFeeEarned: BN;
  stakeLevel: BN[];
  tokensStaked: TokenStakeStats;
  rewardTokensToDistribute: BN;
  rewardTokensPaid: BN;
  tokensToDistribute: BN;
  tokensDistributed: BN;
  lastRewardEpochCount: number;
  rewardTokensDistributed: BN;
  allowRevenueDistribution: number;
  padding: number[];
  revenueTokenAccountBump: number;
  revenuePerFafStaked: BN;
  revenueAccrued: BN;
  revenueDistributed: BN;
  revenuePaid: BN;
  unlockPeriod: BN;
  padding2: BN[];
}

export interface TradeVault {
  tokenMint: PublicKey;
  tokenAccount: PublicKey;
  tokenAmount: BN;
  bump: number;
  tokenAccountBump: number;
  padding: number[];
}

export interface TriggerOrder {
  triggerPrice: OraclePrice;
  triggerSize: BN;
  receiveCustodyUid: number;
}

export interface TriggerQuote {
  exitPrice: OraclePrice;
  profitUsd: BN;
  lossUsd: BN;
  exitFeeUsd: BN;
  receiveUsd: BN;
  isSolvent: boolean;
}

export interface UndelegateCustodyParams {
}

export interface UndelegateInternalOracleParams {
}

export interface UndelegateMarketParams {
}

export interface UndelegatePoolParams {
}

export interface UndelegateReallocVaultParams {
}

export interface UndelegateRebateVaultParams {
}

export interface UndelegateTokenVaultParams {
}

export interface UnstakeInstantLog {
  poolName: string;
  owner: PublicKey;
  unstakeAmount: BN;
  rewardPerLpStaked: BN;
}

export interface UnstakeRequestLog {
  poolName: string;
  owner: PublicKey;
  amount: BN;
}

export interface UnstakeTokenRequestErLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  unstakeAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface UnstakeTokenRequestErParams {
  unstakeAmount: BN;
}

export interface UnstakeTokenRequestLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  unstakeAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
}

export interface UnstakeTokenRequestLogV2 {
  owner: PublicKey;
  tokenStake: PublicKey;
  unstakeAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface UserDepositLedger {
  bump: number;
  padding: number[];
  owner: PublicKey;
  deposits: DepositEntry[];
}

export interface VoltageMultiplier {
  volume: BN;
  rewards: BN;
  rebates: BN;
}

export interface VoltagePointsLog {
  tokenStake: PublicKey;
  voltagePoints: BN;
  rebateUsd: BN;
  voltagePointsType: number;
  benefitsStatus: number;
  padding: number[];
}

export interface Whitelist {
  owner: PublicKey;
  isInitialized: boolean;
  bump: number;
  isSwapFeeExempt: boolean;
  isDepositFeeExempt: boolean;
  isWithdrawalFeeExempt: boolean;
  buffer: number[];
  pool: PublicKey;
}

export interface WithdrawFeesParams {
}

export interface WithdrawInstantFeesParams {
}

export interface WithdrawRequest {
  withdrawableAmount: BN;
  lockedAmount: BN;
  timeRemaining: BN;
}

export interface WithdrawSolFeesParams {
  amount: BN;
}

export interface WithdrawStakeLog {
  poolName: string;
  owner: PublicKey;
  lpTokens: BN;
}

export interface WithdrawTokenErLog {
  owner: PublicKey;
  withdrawRequestId: number;
  amount: BN;
  allowed: boolean;
}

export interface WithdrawTokenLog {
  owner: PublicKey;
  tokenStake: PublicKey;
  withdrawAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
}

export interface WithdrawTokenLogV2 {
  owner: PublicKey;
  tokenStake: PublicKey;
  withdrawAmount: BN;
  currentTimestamp: BN;
  lastUpdatedTimestamp: BN;
  level: number;
  activeStakeAmount: BN;
  levelEligibleAmount: BN;
}

export interface WithdrawTokenReceipt {
  owner: PublicKey;
  tokenMint: PublicKey;
  amount: BN;
  withdrawRequestId: number;
  bump: number;
  processed: number;
  padding: number[];
}

export interface WithdrawTokenSettleBaseLog {
  owner: PublicKey;
  amount: BN;
}

export interface WithdrawTokenWithActionBaseLog {
  owner: PublicKey;
  withdrawRequestId: number;
}

export interface WithdrawTokenWithActionParams {
  withdrawRequestId: number;
}

export interface WithdrawUnclaimedTokensParams {
}

export interface WithdrawalErLog {
  owner: PublicKey;
  mint: PublicKey;
  requestedAmount: BN;
  availableAmount: BN;
  processedAmount: BN;
  ledgerDeductible: BN;
}

export interface WithdrawalEscrowReceipt {
  owner: PublicKey;
  mint: PublicKey;
  amount: BN;
  ledgerDeductible: BN;
  requestedAt: BN;
  processed: number;
  bump: number;
  padding: number[];
}

export interface WithdrawalSettleBaseLog {
  owner: PublicKey;
  tokenMint: PublicKey;
  amount: BN;
  ledgerDeductible: BN;
}

export interface WithdrawalWithActionBaseLog {
  owner: PublicKey;
  tokenMint: PublicKey;
  requestedAmount: BN;
}

export interface WithdrawalWithActionParams {
  amount: BN;
}

// Account structs (same-named entries above):
export type AccountTypeName = "Basket" | "CollectRebateReceipt" | "CollectRevenueReceipt" | "CollectStakeRewardReceipt" | "CollectTokenRewardReceipt" | "CompoundFeesReceipt" | "CompoundingDepositReceipt" | "CompoundingWithdrawReceipt" | "Custody" | "CustodySettlementReceipt" | "CustomOracle" | "FlpStake" | "Market" | "MigrateFlpReceipt" | "MigrateStakeReceipt" | "MoveProtocolFeesReceipt" | "Multisig" | "Order" | "Perpetuals" | "Pool" | "Position" | "ProtocolVault" | "ReallocVault" | "RebateVault" | "Referral" | "SessionTokenV2" | "SettleRebatesReceipt" | "StakingDepositReceipt" | "StakingWithdrawReceipt" | "SwapReceipt" | "TokenStake" | "TokenStakeDepositReceipt" | "TokenVault" | "TradeVault" | "UserDepositLedger" | "Whitelist" | "WithdrawTokenReceipt" | "WithdrawalEscrowReceipt";
