/* eslint-disable */
// Generates src/idl/generatedTypes.ts — concrete TS interfaces from the IDL.
// Plain declarations avoid the TS2589 ("excessively deep") blow-up that
// anchor's generic IdlAccounts/IdlTypes hit on this ~1MB IDL.
//
//   node scripts/generateTypes.js
const fs = require("fs");
const path = require("path");

const idl = require("../src/idl/perpetuals.json");
const OUT = path.join(__dirname, "../src/idl/generatedTypes.ts");

const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
// anchor decodes enum variant tags to camelCase with a lowercase first char.
const lcFirst = (s) => (s ? s.charAt(0).toLowerCase() + s.slice(1) : s);
const variantKey = (s) => lcFirst(camel(s));

function mapType(t) {
  if (typeof t === "string") {
    switch (t) {
      case "bool": return "boolean";
      case "string": return "string";
      case "bytes": return "Buffer";
      case "pubkey":
      case "publicKey": return "PublicKey";
      case "u8": case "u16": case "u32": case "i8": case "i16": case "i32":
        return "number";
      case "u64": case "u128": case "u256": case "i64": case "i128": case "i256":
        return "BN";
      default: return "any";
    }
  }
  if (t.array) return `${mapType(t.array[0])}[]`;
  if (t.vec) return `${mapType(t.vec)}[]`;
  if (t.option) return `(${mapType(t.option)} | null)`;
  if (t.defined) return typeof t.defined === "string" ? t.defined : t.defined.name;
  return "any";
}

const lines = [
  "// AUTO-GENERATED by scripts/generateTypes.js — do not edit by hand.",
  "// Concrete interfaces mirroring the program IDL (anchor camelCase fields).",
  "/* eslint-disable @typescript-eslint/no-explicit-any */",
  'import { BN } from "@coral-xyz/anchor";',
  'import { PublicKey } from "@solana/web3.js";',
  "",
];

for (const ty of idl.types) {
  const def = ty.type;
  if (def.kind === "struct") {
    lines.push(`export interface ${ty.name} {`);
    for (const f of def.fields || []) {
      lines.push(`  ${camel(f.name)}: ${mapType(f.type)};`);
    }
    lines.push("}", "");
  } else if (def.kind === "enum") {
    const variants = (def.variants || []).map(
      (v) => `{ ${variantKey(v.name)}: Record<string, never> }`,
    );
    lines.push(`export type ${ty.name} =`);
    lines.push("  " + (variants.length ? variants.join("\n  | ") : "Record<string, never>") + ";", "");
  }
}

// Account name index → its struct type (struct lives in idl.types under same name).
const typeNames = new Set(idl.types.map((t) => t.name));
const accountNames = idl.accounts.map((a) => a.name).filter((n) => typeNames.has(n));
lines.push("// Account structs (same-named entries above):");
lines.push(`export type AccountTypeName = ${accountNames.map((n) => `"${n}"`).join(" | ")};`);
lines.push("");

fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT}: ${idl.types.length} types, ${accountNames.length} accounts`);
